Setup server
CastelloDev/SvgBackend pull request #6
Opened 2019-09-12 14:11 UTC by MpiloMshengu

2019-09-12 14:55 UTC, hvandermerwe requested changes

2019-09-12 14:55 UTC, hvandermerwe commented on server.js
> +    if(Object.keys(req.body).length>1){
look into implementing a IsNullOrUndefined function for your project, it will make checking this like this a lot easier

2019-09-13 07:07 UTC, sjumba approved these changes

2019-09-13 07:19 UTC, hvandermerwe approved these changes

2019-09-13 08:10 UTC, Andileh approved these changes

2019-09-13 08:15 UTC, merged