Dev
CastelloDev/SvgBackend pull request #7
Opened 2019-11-06 10:22 UTC by sjumba

Now its does send a well encoded base 64 to the front.

2019-11-06 15:15 UTC, CastelloDev requested changes

2019-11-06 15:15 UTC, CastelloDev commented on package.json
> +    "i": "0.3.6",
please remove

2019-11-07 06:30 UTC, sjumba commented on package.json
> +    "i": "0.3.6",
It have been removed.

2019-11-07 07:37 UTC, CastelloDev approved these changes

2019-11-08 07:17 UTC, merged